import {useMemo, useState} from 'react';
import {getData, getHouseFundAccumulated, saveGoalTargets, setGrandmaAccumulated} from '../services/storage';
import {formatINR, percent, parsePaise} from '../utils/format';
import {Icon} from '../components/Icon';

export default function Goals(){
 const [data,setData]=useState(getData()); const [house,setHouse]=useState(String(data.goals.houseFundTarget/100)); const [grandma,setGrandma]=useState(String(data.goals.grandmaKaiUnguraTarget/100)); const [history,setHistory]=useState<{house:number;grandma:number}[]>([]); const houseAccum=getHouseFundAccumulated(); const grandmaAccum=data.goals.grandmaKaiUnguraAccumulated;
 const saveHouse=()=>{const p=parsePaise(house);if(p===null||p<=0)return;setHistory(h=>[...h,{house:data.goals.houseFundTarget,grandma:data.goals.grandmaKaiUnguraTarget}]);saveGoalTargets({houseFundTarget:p,grandmaKaiUnguraTarget:data.goals.grandmaKaiUnguraTarget});setData(getData())};
 const saveGrandma=()=>{const p=parsePaise(grandma);if(p===null||p<0)return;setHistory(h=>[...h,{house:data.goals.houseFundTarget,grandma:data.goals.grandmaKaiUnguraTarget}]);saveGoalTargets({houseFundTarget:data.goals.houseFundTarget,grandmaKaiUnguraTarget:p});setData(getData())};
 const undo=()=>{const prev=history.at(-1);if(!prev)return;saveGoalTargets({houseFundTarget:prev.house,grandmaKaiUnguraTarget:prev.grandma});setHistory(h=>h.slice(0,-1));setData(getData());setHouse(String(prev.house/100));setGrandma(String(prev.grandma/100));};
 const reload=()=>{const d=getData();setData(d);setHouse(String(d.goals.houseFundTarget/100));setGrandma(String(d.goals.grandmaKaiUnguraTarget/100));};
 const grandmaProgress=percent(grandmaAccum,data.goals.grandmaKaiUnguraTarget); const houseProgress=percent(houseAccum,data.goals.houseFundTarget);
 return <><div className="page-heading-row"><div><h1>Goals</h1><p>Plan for what matters. Targets are shared within your workspace; contribution entry will come later.</p></div></div><div className="goals-grid">
  <GoalCard title="HOUSE FUND" description="Funded directly by Puttu's saved CHITS across all workspace accounting periods. Each amount counts once." target={data.goals.houseFundTarget} accumulated={houseAccum} progress={houseProgress} input={house} setInput={setHouse} save={saveHouse} reload={reload} undo={undo} redo={()=>{}} history={history.length} primary/>
  <GoalCard title="GRANDMA — KAI UNGURA" description="An independent personal goal, separate from the monthly ledger." target={data.goals.grandmaKaiUnguraTarget} accumulated={grandmaAccum} progress={grandmaProgress} input={grandma} setInput={setGrandma} save={saveGrandma} reload={reload} undo={undo} redo={()=>{}} history={history.length}/>
 </div><div className="goal-rule-note"><Icon name="target" size={19}/><span><b>Business rule:</b> CHITS is the House Fund. There is no separate House Fund contribution field, and PUTTU remains separate.</span></div></>;
}
function GoalCard({title,description,target,accumulated,progress,input,setInput,save,reload,undo,redo,history,primary=false}:{title:string;description:string;target:number;accumulated:number;progress:number;input:string;setInput:(s:string)=>void;save:()=>void;reload:()=>void;undo:()=>void;redo:()=>void;history:number;primary?:boolean}){const remaining=Math.max(0,target-accumulated);return <section className={`goal-main-card ${primary?'house-card':''}`}><div className="goal-card-title"><h2>{title}</h2><p>{description}</p></div><div className="goal-stat-row"><div><small>Target</small><b>{formatINR(target)}</b></div><div><small>Accumulated</small><b>{formatINR(accumulated)}</b></div><div><small>Remaining</small><b>{formatINR(remaining)}</b></div></div><div className="progress-label-row"><span>Progress</span><b>{progress.toFixed(2)}%</b></div><div className="large-progress"><i style={{width:`${progress}%`}}/></div><label className="goal-input-label">Target amount (₹)<input inputMode="decimal" value={input} onChange={e=>{if(/^\d*(\.\d{0,2})?$/.test(e.target.value))setInput(e.target.value)}}/><small>Empty means ₹0. Save explicitly to update the target.</small></label><button className="small-primary" onClick={save}>Save target</button><div className="history-actions"><button onClick={reload}>Reload record</button><button onClick={undo} disabled={!history}>Undo</button><button onClick={redo} disabled>Redo</button><button onClick={reload}>Refresh history</button></div></section>}
